DATABASE = '/config/recommendations.db'
JELLYFIN_URL = 'https://YOURDOMAINNAMEHERE'
JELLYFIN_API_KEY = 'JELLYFINAPIKEYHERE'
ADMIN_USER_IDS = ['USERID1', 'USERID2']
LOG_FILE = './flask-app.log'
LOG_LEVEL = 'INFO'
